openapi: 3.0.0
info:
  title: API Artistas
  version: 1.0
tags:
  - artista
paths:
  /artista:
    post:
      tags:
        - artista
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artista'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artista'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
      security:
        - JWTAuth: []          
    get:
      tags:
        - artista
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfArtistas'
      security:
        - JWTAuth: []
  /artista/{id}:
    get:
      tags:
        - artista
      parameters:
        - in: path
          type: string
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artista'
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
      security:
        - JWTAuth: []          
    put:
      tags:
        - artista
      parameters:
        - in: path
          type: string
          name: id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artista'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artista'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        422:
          content:
            appication/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
      security:
        - JWTAuth: []
    delete:
      tags:
        - artista
      parameters:
        - in: path
          type: string
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artista'
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
      security:
        - JWTAuth: []    
components:
  securitySchemes:
    JWTAuth:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    ArrayOfArtistas:
      type: array
      items:
        $ref: '#/components/schemas/Artista'
    Artista:
      type: object
      properties:
        autor:
          type: string
        genero:
          type: string
    Mensagem:
      type: object
      properties:
        msg:
          type: string
