openapi: 3.0.0
info:
  title: API Artistas
  version: 1.0
tags:
  - artistas
paths:
  /artistas:
    post:
      tags:
        - artistas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artista'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artista'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
components:
  schemas:
    ArrayOfArtistas:
      type: array
      items:
        $ref: '#/components/schemas/Artista'
    Artista:
      type: object
      properties:
        autor:
          type: string
        genero:
          type: string
    Mensagem:
      type: object
      properties:
        msg:
          type: string
