openapi: 3.0.0
info:
  title: API Artistas
  version: 1.0
tags:
  - artista
paths:
  /artista:
    post:
      tags:
        - artista
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artista'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artista'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
      security:
        - JWTAuth: []          
    get:
      tags:
        - artista
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfArtistas'
      security:
        - JWTAuth: []
  /artista/{id}:
    get:
      tags:
        - artista
      parameters:
        - in: path
          type: string
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artista'
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
      security:
        - JWTAuth: []          
    put:
      tags:
        - artista
      parameters:
        - in: path
          type: string
          name: id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artista'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artista'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        422:
          content:
            appication/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
      security:
        - JWTAuth: []
    delete:
      tags:
        - artista
      parameters:
        - in: path
          type: string
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artista'
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
      security:
        - JWTAuth: []
 /colecoes:
    post:
      summary: Cria uma nova coleção de músicas
      tags:
        - colecoes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Colecao'
      responses:
        201:
          description: Coleção criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Colecao'
        422:
          description: Dados da coleção inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'

    get:
      summary: Retorna todas as coleções de músicas
      tags:
        - colecoes
      responses:
        200:
          description: Lista de todas as coleções
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfColecoes'
        404:
          description: Coleções não encontradas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        400:
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
      security: 
        - JWTAuth: []

  /colecoes/{id}:
    get:
      summary: Retorna uma coleção de músicas pelo ID
      tags:
        - colecoes
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID da coleção
      responses:
        200:
          description: Coleção encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Colecao'
        404:
          description: Coleção não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        400:
          description: ID inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'

    put:
      summary: Atualiza uma coleção de músicas pelo ID
      tags:
        - colecoes
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID da coleção
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Colecao'
      responses:
        200:
          description: Coleção atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Colecao'
        400:
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          description: Coleção não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        422:
          description: Dados da coleção inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'

    delete:
      summary: Remove uma coleção de músicas pelo ID
      tags:
        - colecoes
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID da coleção
      responses:
        204:
          description: Coleção removida com sucesso
        400:
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          description: Coleção não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
/musica:
    post:
      tags:
        - musicas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Musica'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Musica'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
      security:
        - JWTAuth: []
    get:
      tags:
        - musicas
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfMusicas'
      security:
        - JWTAuth: []
  /musica/{id}:
    get:
      tags:
        - musicas
      parameters:
        - in: path
          type: string
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Musica'
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
      security:
        - JWTAuth: []
    put:
      tags:
        - musicas
      parameters:
        - in: path
          type: string
          name: id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Musica'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Musica'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
      security:
        - JWTAuth: []
    delete:
      tags:
        - musicas
      parameters:
        - in: path
          type: string
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Musica'
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
      security:
        - JWTAuth: []    
components:
  securitySchemes:
    JWTAuth:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    ArrayOfArtistas:
      type: array
      items:
        $ref: '#/components/schemas/Artista'
    Artista:
      type: object
      properties:
        autor:
          type: string
        genero:
          type: string
    Mensagem:
      type: object
      properties:
        msg:
          type: string
ArrayOfColecoes:
      type: array
      items:
        $ref: '#/components/schemas/Colecao'
    Mensagem:
      type: object
      properties:
        msg:
          type: string
    Musica:
      type: object
      properties:
        titulo:
          type: string
          description: O título da música
        artista:
          type: string
          description: O artista da música
      example:
        titulo: Música 1
        artista: Artista 1
    Colecao:
      type: object
      required:
        - nome
        - autor
        - musicas
      properties:
        nome:
          type: string
          description: O nome da coleção
        autor:
          type: string
          description: O autor da coleção
        musicas:
          type: array
          items:
            $ref: '#/components/schemas/Musica'
      example:
        nome: Clássicas
        autor: Caio
        musicas:
          - titulo: Música 1
            artista: Artista 1
          - titulo: Música 2
            artista: Artista 2
    ArrayOfMusicas:
      type: array
      items:
        $ref: '#/components/schemas/Musica'
    Musica:
      type: object
      properties:
        titulo:
          type: string
        autor:
          type: string
        genero:
          type: string
    
